[package]
name = "mahjong-enterprise-edition-core"
version = "0.1.0"
authors = ["MasuqaT <occar@hotmail.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
arrayvec = "0.5"
itertools = "0.9"
uuid = { version = "0.8", features = ["v4"] }
